const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const saved = [];
const sent = [];
const widget = { ace(){return this;}, find(){return this;}, addClass(){return this;}, removeClass(){return this;}, ready(){} };
const $ = () => widget;
$.extend = (...args) => Object.assign(...args.filter(value => value !== true));
$.aceOverWatch = { utilities:{isVoid:value=>value===undefined||value===null||value===''}, toast:{show(){}}, net:{save:(helper,data)=>saved.push(data)} };
class Socket { static OPEN=1; constructor(){this.readyState=1;} send(value){sent.push(JSON.parse(value));} close(){this.readyState=3;} }
const context=vm.createContext({$,console,WebSocket:Socket,document:{},window:{},setTimeout:()=>{},getCookie:()=>'',setCookie:()=>{},app_user_id:1,app_clear_cookies:'0',app_ws_esignature_url:'wss://localhost:19111/',app_ws_bcprinter_url:'wss://localhost:8010/',app_base:'https://fixture.invalid'});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../docs/wisemed-client.js'),'utf8'),context);
vm.runInContext('addESIGLogMessage=function(){}; wmESIGConfigWebSocket(); wmESIG.websocket.onopen({}); wmESIGSign({}, "gdpr", "patient-fixture", "Test Only", "NOT-A-REAL-CNP");',context);
assert.equal(sent[0].cmd,'init');
const request=sent[1];
assert.equal(request.cmd,'signpatient');
const response={success:true,forevent:request,data:{sigbase64:Buffer.from('PNG fixture').toString('base64'),id:1,sigenc:JSON.parse(fs.readFileSync(path.join(__dirname,'../../../modules/signingpad/testdata/topaz-sigstring.json'),'utf8')).sigenc}};
context.reply=JSON.stringify(response);
vm.runInContext('wmESIG.websocket.onmessage({data:reply});',context);
assert.equal(saved.length,1);
assert.equal(saved[0]._s_tip,'gdpr');
assert.equal(saved[0]._s_entity_id,'patient-fixture');
assert.equal(saved[0]._s_imagine_b64,response.data.sigbase64);
assert.equal(saved[0]._s_sir_verificare,response.data.sigenc);
context.reply=JSON.stringify({success:false,forevent:request,data:{},error:'signature cancelled'});
vm.runInContext('wmESIG.websocket.onmessage({data:reply});',context);
assert.equal(saved.length,1,'cancel must not trigger database save');
console.log('Original WiseMED JavaScript consumes legacy success/error envelopes and forwards the exact signature fields: PASS');
