// Code generated by gowsdl DO NOT EDIT.

package uploads

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type GetCatalogues struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getCatalogues"`

	PartnerCategory string `xml:"partnerCategory,omitempty" json:"partnerCategory,omitempty"`

	Start soap.XSDDateTime `xml:"start,omitempty" json:"start,omitempty"`
}

type GetCataloguesResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getCataloguesResponse"`

	GetCataloguesReturn []string `xml:"getCataloguesReturn,omitempty" json:"getCataloguesReturn,omitempty"`
}

type Fault RaportariException

type GetProviderInfo struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getProviderInfo"`

	PartnerCategory string `xml:"partnerCategory,omitempty" json:"partnerCategory,omitempty"`

	Start soap.XSDDateTime `xml:"start,omitempty" json:"start,omitempty"`

	Stop soap.XSDDateTime `xml:"stop,omitempty" json:"stop,omitempty"`

	Uic string `xml:"uic,omitempty" json:"uic,omitempty"`
}

type GetProviderInfoResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getProviderInfoResponse"`

	GetProviderInfoReturn []string `xml:"getProviderInfoReturn,omitempty" json:"getProviderInfoReturn,omitempty"`
}

type GetProviderInfoForPhysician struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getProviderInfoForPhysician"`

	PartnerCategory string `xml:"partnerCategory,omitempty" json:"partnerCategory,omitempty"`

	Start soap.XSDDateTime `xml:"start,omitempty" json:"start,omitempty"`

	Stop soap.XSDDateTime `xml:"stop,omitempty" json:"stop,omitempty"`

	Uic string `xml:"uic,omitempty" json:"uic,omitempty"`

	StencilNo string `xml:"stencilNo,omitempty" json:"stencilNo,omitempty"`
}

type GetProviderInfoForPhysicianResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getProviderInfoForPhysicianResponse"`

	GetProviderInfoForPhysicianReturn []string `xml:"getProviderInfoForPhysicianReturn,omitempty" json:"getProviderInfoForPhysicianReturn,omitempty"`
}

type SendReport struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro sendReport"`

	ReportType string `xml:"reportType,omitempty" json:"reportType,omitempty"`

	ReportXML string `xml:"reportXML,omitempty" json:"reportXML,omitempty"`
}

type SendReportResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro sendReportResponse"`

	SendReportReturn int32 `xml:"sendReportReturn,omitempty" json:"sendReportReturn,omitempty"`
}

type GetReportFeedback struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getReportFeedback"`

	FileName string `xml:"fileName,omitempty" json:"fileName,omitempty"`
}

type GetReportFeedbackResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getReportFeedbackResponse"`

	GetReportFeedbackReturn []string `xml:"getReportFeedbackReturn,omitempty" json:"getReportFeedbackReturn,omitempty"`
}

type GetRefund struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getRefund"`

	PartnerCategory string `xml:"partnerCategory,omitempty" json:"partnerCategory,omitempty"`

	Start soap.XSDDateTime `xml:"start,omitempty" json:"start,omitempty"`

	Stop soap.XSDDateTime `xml:"stop,omitempty" json:"stop,omitempty"`

	Uic string `xml:"uic,omitempty" json:"uic,omitempty"`
}

type GetRefundResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getRefundResponse"`

	GetRefundReturn []string `xml:"getRefundReturn,omitempty" json:"getRefundReturn,omitempty"`
}

type GetRefundForPhysician struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getRefundForPhysician"`

	PartnerCategory string `xml:"partnerCategory,omitempty" json:"partnerCategory,omitempty"`

	Start soap.XSDDateTime `xml:"start,omitempty" json:"start,omitempty"`

	Stop soap.XSDDateTime `xml:"stop,omitempty" json:"stop,omitempty"`

	Uic string `xml:"uic,omitempty" json:"uic,omitempty"`

	Stencil string `xml:"stencil,omitempty" json:"stencil,omitempty"`
}

type GetRefundForPhysicianResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getRefundForPhysicianResponse"`

	GetRefundForPhysicianReturn []string `xml:"getRefundForPhysicianReturn,omitempty" json:"getRefundForPhysicianReturn,omitempty"`
}

type GetRefundForInvoice struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getRefundForInvoice"`

	PartnerCategory string `xml:"partnerCategory,omitempty" json:"partnerCategory,omitempty"`

	InvoiceNumber string `xml:"invoiceNumber,omitempty" json:"invoiceNumber,omitempty"`

	InvoiceDate soap.XSDDateTime `xml:"invoiceDate,omitempty" json:"invoiceDate,omitempty"`

	Uic string `xml:"uic,omitempty" json:"uic,omitempty"`
}

type GetRefundForInvoiceResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getRefundForInvoiceResponse"`

	GetRefundForInvoiceReturn []string `xml:"getRefundForInvoiceReturn,omitempty" json:"getRefundForInvoiceReturn,omitempty"`
}

type GetDecisions struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getDecisions"`

	PartnerCategory string `xml:"partnerCategory,omitempty" json:"partnerCategory,omitempty"`

	RequestXml string `xml:"requestXml,omitempty" json:"requestXml,omitempty"`
}

type GetDecisionsResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getDecisionsResponse"`

	GetDecisionsReturn []string `xml:"getDecisionsReturn,omitempty" json:"getDecisionsReturn,omitempty"`
}

type RegisterApplicationInstance struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro registerApplicationInstance"`

	ProvType string `xml:"provType,omitempty" json:"provType,omitempty"`

	Uic string `xml:"uic,omitempty" json:"uic,omitempty"`

	CtrNo string `xml:"ctrNo,omitempty" json:"ctrNo,omitempty"`

	SerialNo string `xml:"serialNo,omitempty" json:"serialNo,omitempty"`

	RegDate soap.XSDDateTime `xml:"regDate,omitempty" json:"regDate,omitempty"`
}

type RegisterApplicationInstanceResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro registerApplicationInstanceResponse"`

	RegisterApplicationInstanceReturn []string `xml:"registerApplicationInstanceReturn,omitempty" json:"registerApplicationInstanceReturn,omitempty"`
}

type IsPhysicianOnContract struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro isPhysicianOnContract"`

	ContractNo string `xml:"contractNo,omitempty" json:"contractNo,omitempty"`

	PhysicianId int64 `xml:"physicianId,omitempty" json:"physicianId,omitempty"`

	AtDate soap.XSDDateTime `xml:"atDate,omitempty" json:"atDate,omitempty"`
}

type IsPhysicianOnContractResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro isPhysicianOnContractResponse"`

	IsPhysicianOnContractReturn string `xml:"isPhysicianOnContractReturn,omitempty" json:"isPhysicianOnContractReturn,omitempty"`
}

type GeneratePrescriptionSeries struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro generatePrescriptionSeries"`

	CategoryCode string `xml:"categoryCode,omitempty" json:"categoryCode,omitempty"`

	OrgUnitCode string `xml:"orgUnitCode,omitempty" json:"orgUnitCode,omitempty"`

	Uic string `xml:"uic,omitempty" json:"uic,omitempty"`

	SubUnitCode string `xml:"subUnitCode,omitempty" json:"subUnitCode,omitempty"`

	ValidFrom soap.XSDDateTime `xml:"validFrom,omitempty" json:"validFrom,omitempty"`

	IsOnLine bool `xml:"isOnLine,omitempty" json:"isOnLine,omitempty"`

	Quantity int32 `xml:"quantity,omitempty" json:"quantity,omitempty"`
}

type GeneratePrescriptionSeriesResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro generatePrescriptionSeriesResponse"`

	GeneratePrescriptionSeriesReturn []string `xml:"generatePrescriptionSeriesReturn,omitempty" json:"generatePrescriptionSeriesReturn,omitempty"`
}

type GetPrescriptionSeriesInfo struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getPrescriptionSeriesInfo"`

	CategoryCode string `xml:"categoryCode,omitempty" json:"categoryCode,omitempty"`

	OrgUnitCode string `xml:"orgUnitCode,omitempty" json:"orgUnitCode,omitempty"`

	Uic string `xml:"uic,omitempty" json:"uic,omitempty"`

	SubUnitCode string `xml:"subUnitCode,omitempty" json:"subUnitCode,omitempty"`
}

type GetPrescriptionSeriesInfoResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getPrescriptionSeriesInfoResponse"`

	GetPrescriptionSeriesInfoReturn []string `xml:"getPrescriptionSeriesInfoReturn,omitempty" json:"getPrescriptionSeriesInfoReturn,omitempty"`
}

type GetPartnerInfo struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getPartnerInfo"`

	PartnerCode string `xml:"partnerCode,omitempty" json:"partnerCode,omitempty"`

	StartDate soap.XSDDateTime `xml:"startDate,omitempty" json:"startDate,omitempty"`

	StopDate soap.XSDDateTime `xml:"stopDate,omitempty" json:"stopDate,omitempty"`

	Uic string `xml:"uic,omitempty" json:"uic,omitempty"`

	SubUnitCode string `xml:"subUnitCode,omitempty" json:"subUnitCode,omitempty"`
}

type GetPartnerInfoResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getPartnerInfoResponse"`

	GetPartnerInfoReturn []string `xml:"getPartnerInfoReturn,omitempty" json:"getPartnerInfoReturn,omitempty"`
}

type GetRegisterFeedbackAggregated struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getRegisterFeedbackAggregated"`

	PartnerUic string `xml:"partnerUic,omitempty" json:"partnerUic,omitempty"`

	PartnerWorkplace string `xml:"partnerWorkplace,omitempty" json:"partnerWorkplace,omitempty"`

	Start soap.XSDDateTime `xml:"start,omitempty" json:"start,omitempty"`

	Stop soap.XSDDateTime `xml:"stop,omitempty" json:"stop,omitempty"`
}

type GetRegisterFeedbackAggregatedResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getRegisterFeedbackAggregatedResponse"`

	GetRegisterFeedbackAggregatedReturn []string `xml:"getRegisterFeedbackAggregatedReturn,omitempty" json:"getRegisterFeedbackAggregatedReturn,omitempty"`
}

type GetRegisterFeedback struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getRegisterFeedback"`

	Filename string `xml:"filename,omitempty" json:"filename,omitempty"`
}

type GetRegisterFeedbackResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getRegisterFeedbackResponse"`

	GetRegisterFeedbackReturn []string `xml:"getRegisterFeedbackReturn,omitempty" json:"getRegisterFeedbackReturn,omitempty"`
}

type SendSupplierData struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro sendSupplierData"`

	SupplierType string `xml:"supplierType,omitempty" json:"supplierType,omitempty"`

	ReportXML string `xml:"reportXML,omitempty" json:"reportXML,omitempty"`
}

type SendSupplierDataResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro sendSupplierDataResponse"`

	SendSupplierDataReturn int64 `xml:"sendSupplierDataReturn,omitempty" json:"sendSupplierDataReturn,omitempty"`
}

type GetSupplierFeedback struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getSupplierFeedback"`

	RefId int64 `xml:"refId,omitempty" json:"refId,omitempty"`
}

type GetSupplierFeedbackResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getSupplierFeedbackResponse"`

	GetSupplierFeedbackReturn []string `xml:"getSupplierFeedbackReturn,omitempty" json:"getSupplierFeedbackReturn,omitempty"`
}

type GetPhysicianCatalogues struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getPhysicianCatalogues"`
}

type GetPhysicianCataloguesResponse struct {
	XMLName xml.Name `xml:"http://webservices.utils.svapnt.siveco.ro getPhysicianCataloguesResponse"`

	GetPhysicianCataloguesReturn []string `xml:"getPhysicianCataloguesReturn,omitempty" json:"getPhysicianCataloguesReturn,omitempty"`
}

type RaportariException struct {
	XMLName xml.Name `xml:"http://exceptions.webservices.utils.svapnt.siveco.ro fault"`

	ErrorCode int32 `xml:"errorCode,omitempty" json:"errorCode,omitempty"`

	Message *string `xml:"message,omitempty" json:"message,omitempty"`
}

type SiuiWS interface {

	// Error can be either of the following types:
	//
	//   - RaportariException

	GetCatalogues(request *GetCatalogues) (*GetCataloguesResponse, error)

	GetCataloguesContext(ctx context.Context, request *GetCatalogues) (*GetCataloguesResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	GetProviderInfo(request *GetProviderInfo) (*GetProviderInfoResponse, error)

	GetProviderInfoContext(ctx context.Context, request *GetProviderInfo) (*GetProviderInfoResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	GetProviderInfoForPhysician(request *GetProviderInfoForPhysician) (*GetProviderInfoForPhysicianResponse, error)

	GetProviderInfoForPhysicianContext(ctx context.Context, request *GetProviderInfoForPhysician) (*GetProviderInfoForPhysicianResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	SendReport(request *SendReport) (*SendReportResponse, error)

	SendReportContext(ctx context.Context, request *SendReport) (*SendReportResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	GetReportFeedback(request *GetReportFeedback) (*GetReportFeedbackResponse, error)

	GetReportFeedbackContext(ctx context.Context, request *GetReportFeedback) (*GetReportFeedbackResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	GetRefund(request *GetRefund) (*GetRefundResponse, error)

	GetRefundContext(ctx context.Context, request *GetRefund) (*GetRefundResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	GetRefundForPhysician(request *GetRefundForPhysician) (*GetRefundForPhysicianResponse, error)

	GetRefundForPhysicianContext(ctx context.Context, request *GetRefundForPhysician) (*GetRefundForPhysicianResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	GetRefundForInvoice(request *GetRefundForInvoice) (*GetRefundForInvoiceResponse, error)

	GetRefundForInvoiceContext(ctx context.Context, request *GetRefundForInvoice) (*GetRefundForInvoiceResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	GetDecisions(request *GetDecisions) (*GetDecisionsResponse, error)

	GetDecisionsContext(ctx context.Context, request *GetDecisions) (*GetDecisionsResponse, error)

	RegisterApplicationInstance(request *RegisterApplicationInstance) (*RegisterApplicationInstanceResponse, error)

	RegisterApplicationInstanceContext(ctx context.Context, request *RegisterApplicationInstance) (*RegisterApplicationInstanceResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	IsPhysicianOnContract(request *IsPhysicianOnContract) (*IsPhysicianOnContractResponse, error)

	IsPhysicianOnContractContext(ctx context.Context, request *IsPhysicianOnContract) (*IsPhysicianOnContractResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	GeneratePrescriptionSeries(request *GeneratePrescriptionSeries) (*GeneratePrescriptionSeriesResponse, error)

	GeneratePrescriptionSeriesContext(ctx context.Context, request *GeneratePrescriptionSeries) (*GeneratePrescriptionSeriesResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	GetPrescriptionSeriesInfo(request *GetPrescriptionSeriesInfo) (*GetPrescriptionSeriesInfoResponse, error)

	GetPrescriptionSeriesInfoContext(ctx context.Context, request *GetPrescriptionSeriesInfo) (*GetPrescriptionSeriesInfoResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	GetPartnerInfo(request *GetPartnerInfo) (*GetPartnerInfoResponse, error)

	GetPartnerInfoContext(ctx context.Context, request *GetPartnerInfo) (*GetPartnerInfoResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	GetRegisterFeedbackAggregated(request *GetRegisterFeedbackAggregated) (*GetRegisterFeedbackAggregatedResponse, error)

	GetRegisterFeedbackAggregatedContext(ctx context.Context, request *GetRegisterFeedbackAggregated) (*GetRegisterFeedbackAggregatedResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	GetRegisterFeedback(request *GetRegisterFeedback) (*GetRegisterFeedbackResponse, error)

	GetRegisterFeedbackContext(ctx context.Context, request *GetRegisterFeedback) (*GetRegisterFeedbackResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	SendSupplierData(request *SendSupplierData) (*SendSupplierDataResponse, error)

	SendSupplierDataContext(ctx context.Context, request *SendSupplierData) (*SendSupplierDataResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	GetSupplierFeedback(request *GetSupplierFeedback) (*GetSupplierFeedbackResponse, error)

	GetSupplierFeedbackContext(ctx context.Context, request *GetSupplierFeedback) (*GetSupplierFeedbackResponse, error)

	// Error can be either of the following types:
	//
	//   - RaportariException

	GetPhysicianCatalogues(request *GetPhysicianCatalogues) (*GetPhysicianCataloguesResponse, error)

	GetPhysicianCataloguesContext(ctx context.Context, request *GetPhysicianCatalogues) (*GetPhysicianCataloguesResponse, error)
}

type siuiWS struct {
	client *soap.Client
}

func NewSiuiWS(client *soap.Client) SiuiWS {
	return &siuiWS{
		client: client,
	}
}

func (service *siuiWS) GetCataloguesContext(ctx context.Context, request *GetCatalogues) (*GetCataloguesResponse, error) {
	response := new(GetCataloguesResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GetCatalogues(request *GetCatalogues) (*GetCataloguesResponse, error) {
	return service.GetCataloguesContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) GetProviderInfoContext(ctx context.Context, request *GetProviderInfo) (*GetProviderInfoResponse, error) {
	response := new(GetProviderInfoResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GetProviderInfo(request *GetProviderInfo) (*GetProviderInfoResponse, error) {
	return service.GetProviderInfoContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) GetProviderInfoForPhysicianContext(ctx context.Context, request *GetProviderInfoForPhysician) (*GetProviderInfoForPhysicianResponse, error) {
	response := new(GetProviderInfoForPhysicianResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GetProviderInfoForPhysician(request *GetProviderInfoForPhysician) (*GetProviderInfoForPhysicianResponse, error) {
	return service.GetProviderInfoForPhysicianContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) SendReportContext(ctx context.Context, request *SendReport) (*SendReportResponse, error) {
	response := new(SendReportResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) SendReport(request *SendReport) (*SendReportResponse, error) {
	return service.SendReportContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) GetReportFeedbackContext(ctx context.Context, request *GetReportFeedback) (*GetReportFeedbackResponse, error) {
	response := new(GetReportFeedbackResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GetReportFeedback(request *GetReportFeedback) (*GetReportFeedbackResponse, error) {
	return service.GetReportFeedbackContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) GetRefundContext(ctx context.Context, request *GetRefund) (*GetRefundResponse, error) {
	response := new(GetRefundResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GetRefund(request *GetRefund) (*GetRefundResponse, error) {
	return service.GetRefundContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) GetRefundForPhysicianContext(ctx context.Context, request *GetRefundForPhysician) (*GetRefundForPhysicianResponse, error) {
	response := new(GetRefundForPhysicianResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GetRefundForPhysician(request *GetRefundForPhysician) (*GetRefundForPhysicianResponse, error) {
	return service.GetRefundForPhysicianContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) GetRefundForInvoiceContext(ctx context.Context, request *GetRefundForInvoice) (*GetRefundForInvoiceResponse, error) {
	response := new(GetRefundForInvoiceResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GetRefundForInvoice(request *GetRefundForInvoice) (*GetRefundForInvoiceResponse, error) {
	return service.GetRefundForInvoiceContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) GetDecisionsContext(ctx context.Context, request *GetDecisions) (*GetDecisionsResponse, error) {
	response := new(GetDecisionsResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GetDecisions(request *GetDecisions) (*GetDecisionsResponse, error) {
	return service.GetDecisionsContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) RegisterApplicationInstanceContext(ctx context.Context, request *RegisterApplicationInstance) (*RegisterApplicationInstanceResponse, error) {
	response := new(RegisterApplicationInstanceResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) RegisterApplicationInstance(request *RegisterApplicationInstance) (*RegisterApplicationInstanceResponse, error) {
	return service.RegisterApplicationInstanceContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) IsPhysicianOnContractContext(ctx context.Context, request *IsPhysicianOnContract) (*IsPhysicianOnContractResponse, error) {
	response := new(IsPhysicianOnContractResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) IsPhysicianOnContract(request *IsPhysicianOnContract) (*IsPhysicianOnContractResponse, error) {
	return service.IsPhysicianOnContractContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) GeneratePrescriptionSeriesContext(ctx context.Context, request *GeneratePrescriptionSeries) (*GeneratePrescriptionSeriesResponse, error) {
	response := new(GeneratePrescriptionSeriesResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GeneratePrescriptionSeries(request *GeneratePrescriptionSeries) (*GeneratePrescriptionSeriesResponse, error) {
	return service.GeneratePrescriptionSeriesContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) GetPrescriptionSeriesInfoContext(ctx context.Context, request *GetPrescriptionSeriesInfo) (*GetPrescriptionSeriesInfoResponse, error) {
	response := new(GetPrescriptionSeriesInfoResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GetPrescriptionSeriesInfo(request *GetPrescriptionSeriesInfo) (*GetPrescriptionSeriesInfoResponse, error) {
	return service.GetPrescriptionSeriesInfoContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) GetPartnerInfoContext(ctx context.Context, request *GetPartnerInfo) (*GetPartnerInfoResponse, error) {
	response := new(GetPartnerInfoResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GetPartnerInfo(request *GetPartnerInfo) (*GetPartnerInfoResponse, error) {
	return service.GetPartnerInfoContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) GetRegisterFeedbackAggregatedContext(ctx context.Context, request *GetRegisterFeedbackAggregated) (*GetRegisterFeedbackAggregatedResponse, error) {
	response := new(GetRegisterFeedbackAggregatedResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GetRegisterFeedbackAggregated(request *GetRegisterFeedbackAggregated) (*GetRegisterFeedbackAggregatedResponse, error) {
	return service.GetRegisterFeedbackAggregatedContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) GetRegisterFeedbackContext(ctx context.Context, request *GetRegisterFeedback) (*GetRegisterFeedbackResponse, error) {
	response := new(GetRegisterFeedbackResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GetRegisterFeedback(request *GetRegisterFeedback) (*GetRegisterFeedbackResponse, error) {
	return service.GetRegisterFeedbackContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) SendSupplierDataContext(ctx context.Context, request *SendSupplierData) (*SendSupplierDataResponse, error) {
	response := new(SendSupplierDataResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) SendSupplierData(request *SendSupplierData) (*SendSupplierDataResponse, error) {
	return service.SendSupplierDataContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) GetSupplierFeedbackContext(ctx context.Context, request *GetSupplierFeedback) (*GetSupplierFeedbackResponse, error) {
	response := new(GetSupplierFeedbackResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GetSupplierFeedback(request *GetSupplierFeedback) (*GetSupplierFeedbackResponse, error) {
	return service.GetSupplierFeedbackContext(
		context.Background(),
		request,
	)
}

func (service *siuiWS) GetPhysicianCataloguesContext(ctx context.Context, request *GetPhysicianCatalogues) (*GetPhysicianCataloguesResponse, error) {
	response := new(GetPhysicianCataloguesResponse)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *siuiWS) GetPhysicianCatalogues(request *GetPhysicianCatalogues) (*GetPhysicianCataloguesResponse, error) {
	return service.GetPhysicianCataloguesContext(
		context.Background(),
		request,
	)
}
